### ISSUE TITLE
Stray period on "Projects" page

### ISSUE THREAD

**Issue by ericabwalker** [codeforkyana/codeforkyana.github.io#1]
There is a stray period on the "Projects" page, after the CFA web address and the "Planned Projects" header. 

<img width="1318" alt="screen shot 2019-03-03 at 6 44 45 pm" src="https://user-images.githubusercontent.com/47954578/53703857-78cc3f00-3de4-11e9-93f9-e6a1bd7020de.png">

**Comment by bretwalker** [comment]
Fixed, thanks!
